### ISSUE TITLE
Ordering of checkerboard corners

### ISSUE THREAD

**Issue by ShreyasSkandanS** [ftdlyc/libcbdetect#1]
Hi,
Great work putting together this library. I noticed that for a lot of my images, the calibration grid corners are ordered differently (not left->right, top->bottom). Am I doing something incorrectly?

Example below:

![Screenshot from 2019-06-14 18-34-13](https://user-images.githubusercontent.com/30153561/59542295-1dc1e200-8ed3-11e9-9e21-5ec46fb236bc.png)

Or Is there any easy fix that you would suggest?

Thanks in advance.

Best regards,
Shreyas

**Comment by ftdlyc** [comment]
Yes, the cornes in cbdetect::Corner are unordered. You can get ordered corners by growing board (cbdetect::boards_from_corners). The corners in a board (cbdetect::Board) are ordered. In the example above, bottom->top, left->right. Rotate the board (cbdetect::Board::idx) 90 degrees clockwise, then it become left->right, top->bottom.  For another image, maybe you should rotate 180 or 270 degrees. You can calculate the rotation angle by comparing the coordinates of the four corners (index 0, 5, 23, 28 in the example).
Sorry, my english is poor. Maybe I didn't explain it clearly.

**Comment by ShreyasSkandanS** [comment]
Hi @ftdlyc thank you for replying to me so quickly. I appreciate it. Please don't apologize, your english is fine. 

I took a look at the result of cbdetect::boards_from_corners and this function prepares the cbdetect::Board object which has **idx** and **energy** variables. Should I order the corners myself using the idx array or is there somewhere that already has the ordered corners?

Thanks for explaining the board rotation, that makes sense to me now.

Also: I'm mainly referring to ordering in terms of consecutive corner labeling. Example in my image the third row is 12-**29**-13-14-15-16 instead of 12-13-14-15-16-17.

**Comment by ftdlyc** [comment]
cbdetect::Board::idx is a two dimension array. In your image the array is
[ 23  17  12   6   0
  24  18  29   7   1
......
  28  22  16  11  5 ]

As you can see, the first row in the 2d mat corresponde to the first column in your image. So what you need to do is to change the indexes 28-17-12-6-0 to 0-1-2-3-4. For example:

```
// detect
cbdetect::Corner corners;  
std::vector<cbdetect::Board> all_boards;  
cbdetect::find_corners(img, corners, params);  
cbdetect::boards_from_corners(img, corners, all_boards, params);

// choose the first chessboard
// maybe you shoule rotate 90, 180, 270 degrees
auto board = all_boards[0].idx;

// create a new array
cbdetect::Corner ordered_corners;

for(int i = 0; i < board.size(); ++i) {
  for(int j = 0; j < board[0].size(); ++j) {
    int index = board[i][j];
    if(index < 0) continue;
    
    // copy corner
    ordered_corners.p.emplace_back(corners.p[index]); // p is the coordinate of this corner
    ordered_corners.r.emplace_back(corners.r[index]);
    ordered_corners.v1.emplace_back(corners.v1[index]);
    ordered_corners.v2.emplace_back(corners.v2[index]);
    ordered_corners.score.emplace_back(corners.score[index]);
  }
}

cbdetect::plot_corners(img, ordered_corners);
cv::waitKey();
```

**Comment by ShreyasSkandanS** [comment]
Thank you very much @ftdlyc. Thanks for the example and for creating this repository!
