### ISSUE TITLE
What is the principle that saddle points are corner points ？

### ISSUE THREAD

**Issue by mhzhou2021** [ftdlyc/libcbdetect#4]
What is the principle that saddle points are corner points  the following code？ths       
 // saddle point is the corner
        double dx = (k.at<double>(2, 0) * k.at<double>(4, 0) - 2 * k.at<double>(1, 0) * k.at<double>(3, 0)) / det;
        double dy = (k.at<double>(2, 0) * k.at<double>(3, 0) - 2 * k.at<double>(0, 0) * k.at<double>(4, 0)) / det;

        u_cur += dx;
        v_cur += dy;

        double dist = std::sqrt((u_cur - u_init) * (u_cur - u_init) + (v_cur - v_init) * (v_cur - v_init));
        if(dist > r) {
          is_saddle_point = false;
          break;
        }
        if(std::sqrt(dx * dx + dy * dy) <= eps) {
          break;
        }

**Comment by ftdlyc** [comment]
You can see this paper Firgure (2). The suface arround corner is saddle surface.
https://openaccess.thecvf.com/content_ICCV_2017/papers/Ha_Deltille_Grids_for_ICCV_2017_paper.pdf
